TradingApp/TradingClient/Trading.Presentation.Website/Controllers/PortfolioController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Trading.Business.Logic.Interfaces;
using Trading.Common.Dto;
using Trading.Presentation.Website.Models;

namespace Trading.Presentation.Website.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly IPortfolioBl _portfolioLogic;
        private readonly IMapper _mapper;

        public PortfolioController(IPortfolioBl portfolioLogic, IMapper mapper)
        {
            _portfolioLogic = portfolioLogic;
            _mapper = mapper;
        }
        // GET: PortfolioController
        public async Task<ActionResult> Index()
        {
            var result = await _portfolioLogic.GetAll();
            return View(_mapper.Map<IEnumerable<PortfolioViewModel>>(result));

        }

        // GET: PortfolioController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PortfolioController/Create
        public async Task<ActionResult> Create(string name, string symbol)
        {
            PortfolioViewModel portfolio = new ();
            portfolio.Stock = new() { Name = name, Symbol = symbol };
            return View(portfolio);
        }

        // POST: PortfolioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string name, string symbol, [Bind("Amount","BuyPrice","BuyDate")] PortfolioViewModel portfolio)
        {
            try 
            {
                portfolio.Stock = new() { Name = name, Symbol = symbol };
                await _portfolioLogic.Add(_mapper.Map<PortfolioDto>(portfolio));
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PortfolioController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PortfolioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PortfolioController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PortfolioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TradingApp/TradingClient/Trading.Presentation.Website/Controllers/StockController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Trading.Business.Logic.Interfaces;
using Trading.Common.Dto;
using Trading.Common.Dto.Pagination;
using Trading.Presentation.Website.Models;
using Trading.Presentation.Website.Models.Pagination;

namespace Trading.Presentation.Website.Controllers
{
    public class StockController : Controller
    {
        private readonly IStockBl _stockLogic;
        private readonly IMapper _mapper;

        public StockController(IStockBl stockLogic, IMapper mapper)
        {
            _stockLogic = stockLogic;
            _mapper = mapper;
        }

        // GET: StockController
        public async Task<ActionResult> Index([Bind("PageNumber", "PageSize")] PaginationFilterViewModel paginationFilter)
        {
            var result = await _stockLogic.GetAll(_mapper.Map<PaginationFilterDto>(paginationFilter));
            return View(_mapper.Map<PagedResponseViewModel<IEnumerable<StockViewModel>>>(result));

        }

        // GET: StockController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StockController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StockController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StockController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StockController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StockController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StockController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TradingApp/TradingClient/Trading.Presentation.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trading</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Trading.Presentation.Website.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-wallet2"> </i>Trading</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="Index" asp-route-pageNumber ="1" asp-route-pageSize="15">Stocks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Portfolio" asp-action="Index">Portfolio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Trading.Presentation.Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>